name: Issues
on:
    issues:
        types: 'opened'
jobs:
    details:
        runs-on: ubuntu-latest
        steps:
            - name: Show Issue Details
              run: echo ${{ github.event.issue.body }}